### ISSUE TITLE
Files not updating

### ISSUE THREAD

**Issue by ajxcameron** [mexicovid19/Mexico-datos#23]
The Mexico data files haven't updated in two days.

**Comment by rodrigolece** [comment]
Fixed this morning in 89fc911

**Comment by rodrigolece** [comment]
I don't know what went wrong yesterday but I had to update it manually today. Sorry, can I ask if you are using our files in something that is crucially dependent on having the data each day? Because I could help you set up your own local version of the files generated with our code. The processing code is there and there is an extra bit in bash for downloading the data and doing the commits and I would gladly share that with you if you need. Otherwise, we're happy that you are using our data!
